app:
  env: "production"  # development, testing, production
  port: 8000
  version: 0.1.0
  max_attachment_size: 26214400  # 25MB in bytes (25 * 1024 * 1024)
  allowed_file_types:
    extensions: [".pdf", ".docx", ".xlsx", ".pptx", ".eml", ".txt"]
    mime_types: 
      - "application/pdf"
      - "application/vnd.openxmlformats-officedocument.*"
      - "text/plain"
      - "message/rfc822"

# Celery configuration
celery:
  broker_url: "redis://localhost:6379/0"
  result_backend: "redis://localhost:6379/0"
  timezone: "Asia/Singapore"
  beat_schedule:
    # Example scheduled task that runs every 30 minutes
    cleanup_expired_jobs:
      task: "app.celery.tasks_maintenance.cleanup_expired_jobs"
      schedule: 1800  # 30 minutes in seconds
      options:
        queue: "maintenance"
    
    # Example scheduled task that runs at midnight
    generate_daily_stats:
      task: "app.celery.tasks_reporting.generate_daily_stats"
      schedule: 
        type: "crontab"
        hour: "0"
        minute: "0"
      options:
        queue: "reporting"

rate_limits:
  tiers:
    free:
      requests_per_minute: 10
      max_concurrent: 2
    pro:
      requests_per_minute: 100
      max_concurrent: 20
    enterprise:
      requests_per_minute: 1000
      max_concurrent: 100

openai:
  max_tokens_per_request: 4096
  monthly_cost_limit: 100  # USD
  model_choices:
    - "gpt-4o-mini"
    - "gpt-3.5-turbo-1106"
  fallback_model: "gpt-4o-mini"

email_analysis:
  department_keywords:
    IT: ["software", "hardware", "server", "network", "computer", "technology", "technical", "IT"]
    HR: ["hiring", "recruitment", "employee", "benefits", "hr", "personnel", "training", "onboarding"]
    Finance: ["budget", "payment", "invoice", "financial", "accounting", "expense", "finance", "cost"]
    Legal: ["contract", "agreement", "compliance", "law", "legal", "policy", "regulation", "terms"]
    Marketing: ["campaign", "advertisement", "social media", "marketing", "promotion", "brand", "market"]
    Sales: ["customer", "client", "sale", "opportunity", "lead", "deal", "revenue", "prospect"]
    Operations: ["operations", "logistics", "supply chain", "procurement", "facility", "warehouse"]
    Product: ["product", "feature", "roadmap", "design", "user experience", "development", "release"]

notifications:
  email:
    enabled: false
    smtp_server: "smtp.example.com"
    smtp_port: 587
    sender: "noreply@mailanalyzer.com"
    recipients: ["devops@company.com"]
  log_file:
    path: "logs/errors.log"
    max_size: 100MB
    backup_count: 5
